ollama_url: http://192.168.5.248:11434

dify_user: user123
dify_url: http://192.168.5.54:5001
dify_api_paper_detect: app-5ouBKP8R81FXAjBgSg3kblfr
dify_api_paper_tag: app-4CUMRTiIUHOczjhSx6I4V8QZ

searxng_host: http://192.168.5.54:8080

paperless_url: http://192.168.5.54:8000
paperless_token: 788eeac855368cf6050554e31df26f9f0adfe5ed

save_paper: true
cache_dir: src/papers
